// <auto-generated />
using System;
using GameClubProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameClubProject.Migrations
{
    [DbContext(typeof(GameclubDBContext))]
    partial class GameclubDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GameClubProject.Models.IgdbApi", b =>
                {
                    b.Property<int>("PKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pKey")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IgdbClientId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("IGDB_CLIENT_ID");

                    b.Property<string>("IgdbClientSecret")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("IGDB_CLIENT_SECRET");

                    b.HasKey("PKey")
                        .HasName("PK__IGDB_API__4866A5D74AC7DE72");

                    b.ToTable("IGDB_API");
                });

            modelBuilder.Entity("GameClubProject.Models.MembershipStatus", b =>
                {
                    b.Property<int>("PKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pKey")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<int>("MembershipStatusId")
                        .HasColumnType("int")
                        .HasColumnName("membershipStatusID");

                    b.HasKey("PKey")
                        .HasName("PK__membersh__4866A5D728304AAD");

                    b.HasIndex(new[] { "MembershipStatusId" }, "UQ__membersh__19137F515B6CBCD7")
                        .IsUnique();

                    b.HasIndex(new[] { "Description" }, "UQ__membersh__489B0D977BE934CA")
                        .IsUnique();

                    b.ToTable("membershipStatus");
                });

            modelBuilder.Entity("GameClubProject.Models.PersonalUserTrackedGame", b =>
                {
                    b.Property<int>("PKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pKey")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("gameID");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("userID");

                    b.HasKey("PKey")
                        .HasName("PK__personal__4866A5D7FE24FF2F");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("personalUserTrackedGames");
                });

            modelBuilder.Entity("GameClubProject.Models.UserAccount", b =>
                {
                    b.Property<int>("PKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pKey")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressCity")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("addressCity");

                    b.Property<string>("AddressState")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("addressState");

                    b.Property<string>("AddressStreet")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("addressStreet");

                    b.Property<string>("AddressStreet2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("addressStreet2");

                    b.Property<string>("AddressZipCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("addressZipCode");

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("lastName");

                    b.Property<int?>("MembershipStatusId")
                        .HasColumnType("int")
                        .HasColumnName("membershipStatusID");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("userID");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("userName");

                    b.HasKey("PKey")
                        .HasName("PK__userAcco__4866A5D77FE73871");

                    b.HasIndex("MembershipStatusId");

                    b.HasIndex(new[] { "UserName" }, "UQ__userAcco__66DCF95CB977994E")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__userAcco__AB6E616446AD2B02")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "UQ__userAcco__CB9A1CDEA43BF1A1")
                        .IsUnique();

                    b.ToTable("userAccount");
                });

            modelBuilder.Entity("GameClubProject.Models.UserGamerTag", b =>
                {
                    b.Property<int>("PKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pKey")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GamerTag")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("gamerTag");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("userID");

                    b.HasKey("PKey")
                        .HasName("PK__userGame__4866A5D72D774886");

                    b.HasIndex("UserId");

                    b.ToTable("userGamerTags");
                });

            modelBuilder.Entity("GameClubProject.Models.VideoGameMain", b =>
                {
                    b.Property<int>("PKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pKey")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("gameID");

                    b.HasKey("PKey")
                        .HasName("PK__videoGam__4866A5D71B0443C9");

                    b.HasIndex(new[] { "GameId" }, "UQ__videoGam__DA90B4B3C75AA614")
                        .IsUnique();

                    b.ToTable("videoGameMain");
                });

            modelBuilder.Entity("GameClubProject.Models.VideoGameUserContent", b =>
                {
                    b.Property<int>("PKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pKey")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("gameID");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("userID");

                    b.Property<decimal>("UserRating")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("userRating");

                    b.Property<string>("UserReview")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("userReview");

                    b.HasKey("PKey")
                        .HasName("PK__videoGam__4866A5D7C9368B34");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("videoGameUserContent");
                });

            modelBuilder.Entity("GameClubProject.Models.PersonalUserTrackedGame", b =>
                {
                    b.HasOne("GameClubProject.Models.VideoGameMain", "Game")
                        .WithMany("PersonalUserTrackedGames")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK__personalU__gameI__37A5467C")
                        .HasPrincipalKey("GameId")
                        .IsRequired();

                    b.HasOne("GameClubProject.Models.UserAccount", "User")
                        .WithMany("PersonalUserTrackedGames")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__personalU__userI__36B12243")
                        .HasPrincipalKey("UserId")
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameClubProject.Models.UserAccount", b =>
                {
                    b.HasOne("GameClubProject.Models.MembershipStatus", "MembershipStatus")
                        .WithMany("UserAccounts")
                        .HasForeignKey("MembershipStatusId")
                        .HasConstraintName("FK__userAccou__membe__34C8D9D1")
                        .HasPrincipalKey("MembershipStatusId");

                    b.Navigation("MembershipStatus");
                });

            modelBuilder.Entity("GameClubProject.Models.UserGamerTag", b =>
                {
                    b.HasOne("GameClubProject.Models.UserAccount", "User")
                        .WithMany("UserGamerTags")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__userGamer__userI__35BCFE0A")
                        .HasPrincipalKey("UserId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameClubProject.Models.VideoGameUserContent", b =>
                {
                    b.HasOne("GameClubProject.Models.VideoGameMain", "Game")
                        .WithMany("VideoGameUserContents")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK__videoGame__gameI__398D8EEE")
                        .HasPrincipalKey("GameId")
                        .IsRequired();

                    b.HasOne("GameClubProject.Models.UserAccount", "User")
                        .WithMany("VideoGameUserContents")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__videoGame__userI__38996AB5")
                        .HasPrincipalKey("UserId")
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameClubProject.Models.MembershipStatus", b =>
                {
                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("GameClubProject.Models.UserAccount", b =>
                {
                    b.Navigation("PersonalUserTrackedGames");

                    b.Navigation("UserGamerTags");

                    b.Navigation("VideoGameUserContents");
                });

            modelBuilder.Entity("GameClubProject.Models.VideoGameMain", b =>
                {
                    b.Navigation("PersonalUserTrackedGames");

                    b.Navigation("VideoGameUserContents");
                });
#pragma warning restore 612, 618
        }
    }
}
